### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by FlorentChamault** [atoponce/d-note#48]
Hi, 
i have a problem, dnote doesn't work. 
i have a error message log
Traceback (most recent call last):
[Mon Jun 06 15:24:47 2016] [error] [client ]   File "/var/www/pwgen/dnote.wsgi", line 5, in <module>
[Mon Jun 06 15:24:47 2016] [error] [client ]     from dnote import DNOTE as application
[Mon Jun 06 15:24:47 2016] [error] [client ]   File "/usr/local/lib/python2.7/dist-packages/dnote-1.0.1-py2.7.egg/dnote/**init**.py", line 3, in <module>
[Mon Jun 06 15:24:47 2016] [error] [client ]     import utils
[Mon Jun 06 15:24:47 2016] [error] [client ]   File "/usr/local/lib/python2.7/dist-packages/dnote-1.0.1-py2.7.egg/dnote/utils.py", line 4, in <module>
[Mon Jun 06 15:24:47 2016] [error] [client ]     from note import data_dir
[Mon Jun 06 15:24:47 2016] [error] [client ]   File "/usr/local/lib/python2.7/dist-packages/dnote-1.0.1-py2.7.egg/dnote/note.py", line 47, in <module>
[Mon Jun 06 15:24:47 2016] [error] [client ]     os.sys.exit(1)
[Mon Jun 06 15:24:47 2016] [error] [client ] SystemExit: 1

Can you help me ? 
Thanks

**Comment by JacobTheEvans** [comment]
I have never gotten this software to work properly but your error seems to be this line "import utils". So I would try installing it through pip.
 pip install utils

**Comment by btaub** [comment]
I ran into this as well. Make sure the directory for your config (should be either /etc/dnote or ~/.dnote) is owned by the same user that your web server runs as, usually www-data or similar.

**Comment by thxmike** [comment]
I am getting this same exact error. I tried updating the perms. This did not help. I tried the pip installer and this did not work either. Any assistance would be appreciated.
